### ISSUE TITLE
VoiceOver output is not automatically read in iOS 14.8 (iPhone 7)

### ISSUE THREAD

**Issue by sukiletxe** [erkyrath/iosglk#4]
Steps:
1. Open either Dreamhold or Hadean Lands.
2. Press space until the prompt appears, then type`l`, or `i` several times (type these commands, not letters).

Expected: Voiceover reads the updated part of the area of the adventure.

Actual: Although it worked first time, subsequently it only read the inputted commands with a lower pitch (as if they were deleted). Also it seems to automatically read italics only in Hadean lands (that is, when going through the introductory text italics are read).

In case anybody reads this before it is fixed, you can buy or download hadean lands, shade or the dreamhold for any other platform and play them for frotz for iOS, which works fine (you won't get the additional screens, of course).

**Comment by erkyrath** [comment]
Thanks for the note. I'm afraid that I've dropped support for iosglk, and thus also for Hadean Lands and my other iOS IF apps. See https://blog.zarfhome.com/2020/01/iosglk-iosglulxe-and-iosfizmo-are-out.html

**Comment by sukiletxe** [comment]
OK, sad but totally understandable. Thanks for making these apps, they helped me discover hadean lands (and lots of content in the dreamhold, too). I will close this now, but it would be helpful to add a note in the description telling that automatic reading with voiceOver may not be supported in later iOS versions (as the rest works fine). I don't know when it started not working, sadly.
